### ISSUE TITLE
Enable sharing of requests to channel and not just the requesting user?

### ISSUE THREAD

**Issue by rundro** [kiranshila/Doplarr#104]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kiranshila** [comment]
This is controllable using the `DISCORD__REQUESTED_MSG_STYLE` variable from https://kiranshila.github.io/Doplarr/#/configuration?id=optional-settings
