### ISSUE TITLE
JAR file not respecting my config.edn options

### ISSUE THREAD

**Issue by rundro** [kiranshila/Doplarr#118]
**Describe the bug**
I can fill out the config.edn file with my options but in discord the bot will still prompt me for my profile and root folder selection, i've specified them in the config file. It's also not respecting my partial seasons, season folders, and msg style options. I am using the JAR file as a system service. I've also tried using the "id" value of each profile/root folder with no luck.

**Expected behavior**
The bot accepts my config.edn defined options and doesnt prompt me for those details when requesting in discord.

**Screenshots**
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/52337715/215927273-ac6093da-5189-4786-aaa1-1b57369f88af.png">

<img width="485" alt="image" src="https://user-images.githubusercontent.com/52337715/215927432-fbd27ea9-1039-4dc9-a941-8cd08164ac8d.png">

**Logs**
Please copy out the log in it's entirety, please make sure to hide any potential secrets/API keys - although they should be censored via the logging program.
```
Jan 31 20:38:21 samsung java[391500]: 2023-02-01T01:38:21.894Z samsung INFO [doplarr.core:38] - Discord connection successful
Jan 31 20:38:21 samsung java[391500]: 2023-02-01T01:38:21.913Z samsung INFO [doplarr.core:43] - Connected to guild
Jan 31 20:38:22 samsung java[391500]: 2023-02-01T01:38:22.060Z samsung INFO [doplarr.core:43] - Connected to guild
Jan 31 20:38:22 samsung java[391500]: 2023-02-01T01:38:22.167Z samsung INFO [doplarr.core:43] - Connected to guild
Jan 31 20:39:37 samsung java[391500]: 2023-02-01T01:39:37.904Z samsung INFO [doplarr.interaction-state-machine:28] - Performing search for series andor


Jan 31 20:53:53 samsung java[391500]: 2023-02-01T01:53:53.772Z samsung INFO [doplarr.interaction-state-machine:28] - Performing search for series andor
Jan 31 20:54:15 samsung java[391500]: 2023-02-01T01:54:15.003Z samsung INFO [doplarr.interaction-state-machine:112] - Performing request for  {:title "Andor", :year 2022, :tvdb-id 393189, :season-folder false, :season 1, :quality-profile-id 7, :language-profile-id 1, :rootfolder-id 3}
```

**Additional context**
Communicates fine with discord which is odd, so it sees the discord token. It just wont respect the optional settings in the config. Says its a valid config file on startup.

```
java -version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)
```

**Comment by kiranshila** [comment]
Semicolons are comments in the EDN format, you should remove them if you don't want those lines commented out.

**Comment by rundro** [comment]
Woof not one of my finer moments here. Thank you!
