### ISSUE TITLE
[Feature Request] Add Notification System for Request Availability

### ISSUE THREAD

**Issue by Matthunker** [kiranshila/Doplarr#144]
**Is your feature request related to a problem? Please describe.**
Yes, currently there is no notification system to alert users when a requested feature or update becomes available. This means users have to manually check for updates or availability, which can be inefficient and lead to missed updates.

**Describe the solution you'd like**
I would like to request a notification feature for Doplarr. When a request is available, the bot should send a notification to the user who made the request. This would ensure users are promptly informed and can take action without needing to continuously check the status manually.

**Describe alternatives you've considered**
An alternative could be to provide a periodic status update (e.g., daily or weekly) summarizing the availability of requests. However, this approach might still lead to delays compared to a real-time notification system.

**Additional context**
Implementing this feature would enhance user experience by ensuring timely notifications and reducing the need for users to check manually. It would be helpful if notifications could be sent via a preferred channel, direct messages, or notifications within the same request via an edit.

**Comment by Matthunker** [comment]
Overseer has this feature as a webhook, request no longer needed.

**Comment by Matthunker** [comment]
Overseer has this feature as a webhook, request no longer needed.

**Comment by Daxiongmao87** [comment]
I would say this would still make sense as a feature.  Especially since not all members may have a discord account and the service is forced to use the doplarr-fallback account on overseerr.

Just like how it @'s a particular user about a request being made, it would be nice to have it @ that same user for when that request is available.
