### ISSUE TITLE
Help with bot config

### ISSUE THREAD

**Issue by ryansg8** [kiranshila/Doplarr#15]
Hey, pulled this on docker to check it out seems pretty cool!

I am a bit of a docker noob so I am not really 100% what I am doing, but how exactly would you go about finding the config.eon, like where is that stored for the docker container? My only issue is that I need to change the quality profile so it isn't constantly trying to download 60GB files. Thanks for the help and look forward to using this!

**Comment by kiranshila** [comment]
Welcome! Thanks for trying out my bot.

You do not need a separate config file if you are using this with Docker. All you need to do is fill out the missing bits in https://github.com/kiranshila/Doplarr#running-with-docker and you should be good to go.

**Comment by kiranshila** [comment]
I'm working on solving the profile bit right now, but if there are files that are too big in general, that should be an adjustment in radarr/sonarr.

**Comment by ryansg8** [comment]
> I'm working on solving the profile bit right now, but if there are files that are too big in general, that should be an adjustment in radarr/sonarr.

Yeah so my biggest issue is that it's default to the any profile which likes to get 4k 60gb movies. So you are saying as it stands currently we cannot change the default download profile from any on docker?

**Comment by kiranshila** [comment]
The latest version lets you pick the profile now. Check it out!

I'm saying in general you can put an upper limit on the file sizes in the radarr/sonarr profiles. Like I think I have 20gb/hr limit on 4K so I don't end up with giant files.
