### ISSUE TITLE
Set default quality profile for sonarr/radarr

### ISSUE THREAD

**Issue by fredrikburmester** [kiranshila/Doplarr#36]
Description of current behaviour:
When requesting a movie or tv-show (sonarr/radarr) the user needs to choose the quality profile. 

Enhancement:
Implement a default quality profile for sonarr/radarr so the user won't have to choose. This is especially nice when there is only one profile

<img width="480" alt="Screenshot 2021-09-28 at 10 30 04" src="https://user-images.githubusercontent.com/26228321/135052129-987feac0-43ee-4f41-bb5b-b351d02397c3.png">

**Comment by kiranshila** [comment]
Yeah absolutley selections with only one options should be settable. This is fixed in the upcoming release, which I hope to finish soon.

**Comment by kiranshila** [comment]
This is now settable in the latest release with the optional env variables. Also, there won't be a dropdown for options with only one selection now
