### ISSUE TITLE
Strip surplus forward slash from env URL's

### ISSUE THREAD

**Issue by bradcornford** [kiranshila/Doplarr#39]
Environment URL's with surplus forward slashes causes search to always return empty results. With the message `Search result returned no hits`

Example URL: http://192.168.1.2:8989/

**Comment by kiranshila** [comment]
Oh good find! Yeah we certainly need to sanitize the URLs

**Comment by kiranshila** [comment]
An error is now thrown on invalid URLs in the latest release
