### ISSUE TITLE
Request for series with too many seasons never load

### ISSUE THREAD

**Issue by MarcStocker** [kiranshila/Doplarr#43]
When requesting a series with too many seasons (I'm guessing 25+ seasons), the "Which season?" prompt never appears.  

Examples that replicate this behavior:
- Survivor (2000) (41 Seasons)
- Dr. Who (1963) (26 Seasons)
- The Simpsons  (33 Seasons)

Example that works as expected:
- South Park (24 Seasons)

After selecting the series, it thinks for a second (3 animated dots next to the select box), but the bot does not update to display the season selection menu. 

The following screenshot contains an attempted request for "Survivor", "South Park" and "Dr. Who", in that order. 

![image](https://user-images.githubusercontent.com/16886667/148157749-6dd64ae6-ef45-4190-9885-6dd0a642f58e.png)

**Comment by kiranshila** [comment]
Interesting. Was there any error message in the log? I'll dig into this.

**Comment by MarcStocker** [comment]
Nothing popped up in the Docker logs, and not sure where to look for additional log files. 
If it's possible to see them from the docker container I'd be happy to provide them.

**Comment by kiranshila** [comment]
So the maximum number of selection items according the discord api is 25, I need to think about this more....

**Comment by kiranshila** [comment]
Fixed in the latest release!
