### ISSUE TITLE
Show requests publicly in specified channel

### ISSUE THREAD

**Issue by stephanrenggli** [kiranshila/Doplarr#59]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to limit requests to certain channels and have an option to publicly show the requests in that channel. With slash commands only the person executing the command can see it (as far as I know).

**Describe the solution you'd like**
Add a setting to limit requests in a specific channel and/or publicly show requests in a specified channel.

**Describe alternatives you've considered**
None, just a nice-to-have feature, not required in any way.

**Additional context**
I was using requestrr before and it would be nice to have the same option again with this application.

**Comment by kiranshila** [comment]
As far as I'm aware, currently restricting slash commands to certain channels isn't supported by discord https://github.com/discord/discord-api-docs/issues/2324

As far as showing requests, you can set `DISCORD__REQUESTED_MSG_STYLE` to one of `:plain` or `:embed` to get a public response (it should be `:plain` by default

**Comment by stephanrenggli** [comment]
Ah I see. Maybe this was only an option before Requestrr switched to slash commands.
Public response works as expected. Thanks!

**Comment by kiranshila** [comment]
Closing for now - as far as posting in a different channel is concerned, I believe that is not possible with a simple slash command bot as the bot only has access to the invoked context.
