### ISSUE TITLE
Typo in optional settings matrix in readme file.

### ISSUE THREAD

**Issue by maximuskowalski** [kiranshila/Doplarr#63]
In the optional settings section of the readme the  Sonarr Language Profile is described as being a language profile for radarr, not sonarr.

`SONARR__LANGUAGE_PROFILE`

`The name of the language profile to use by default for Radarr`

I am unsure on etiquette for readme file typos, my apologies if your preference is for a PR.

**Comment by kiranshila** [comment]
I love PRs! I'd need a formal etiquette if anyone actually submitted any haha. So yeah, please submit a PR, that'd be great!
