### ISSUE TITLE
Not sure if bad configuration or bug?

### ISSUE THREAD

**Issue by AleAlejandrok** [kiranshila/Doplarr#69]
I was testing the bot in another test server and then added him to my main server. I am using Overseer and got everything working on the test server. When I added him to the main server he spit this error out. 

Troubleshooting taken: restarted the bot while he was joined to the main server and while he wasn't. Kicked him from the test server. The only other bot running slash commands on the main server is muse.

Thank you for this project! I hope I am not being silly and overlooking something incredibly grave.

==============================================
2022-03-22T14:35:40.104Z 9700eab42371 FATAL [doplarr.discord:159] - Error in registering commands

[37mjava.lang.Thread.run[m [32m Thread.java: 831[m
[37mjava.util.concurrent.ThreadPoolExecutor$Worker.run[m [32mThreadPoolExecutor.java: 630[m
[37mjava.util.concurrent.ThreadPoolExecutor.runWorker[m [32mThreadPoolExecutor.java: 1130[m
[37m...[m [32m [m
[33mclojure.core/binding-conveyor-fn/[1;33mfn[m [32m core.clj: 2038[m
[33mdiscljord.messaging.impl/step-agent/[1;33mfn[m [32m impl.clj: 1191[m
[33mdiscljord.messaging.impl/[1;33mmake-request![m [32m impl.clj: 1146[m
[33mdiscljord.messaging.impl/make-request!/[1;33mmake-request[m [32m impl.clj: 1141[m
[37m...[m [32m [m
[33mdiscljord.messaging.impl/[1;33mfn[m [32m impl.clj: 905[m
[1;31mclojure.lang.ExceptionInfo[m: [3mAttempted to overwrite with invalid guild commands[m
[1mcode[m: 50001
[1mmessage[m: "Missing Access"

**Comment by kiranshila** [comment]
This certainly seems like a configuration issue - make sure you've enabled both `applications.commands` and `bot` when you created the invite link
