### ISSUE TITLE
Allow modification of allowed Root Folders

### ISSUE THREAD

**Issue by ManveerBhullar** [kiranshila/Doplarr#73]
Some people have multiple root folders defined in sonarr/radarr/etc for their media. When requesting via Doplarr, there could be a default setting depending on series/movie type.

This can be useful for when you don't want requesters to see some root paths.

Example:
You have 3 rooth paths defined in Sonarr
- /media/smallDrive/television
- /media/mediumDrive/television
- /media/largeDrive/television

If smallDrive is full, you wouldn't want requesters to set that as the path. It would be useful to remove that as an option. 

Depnding on request type (ie, anime) , maybe there can also be a default path.
Exposing less options to users is a general good rule imo.

**Comment by azzuron** [comment]
I agree. I do not want users choosing which path to store items as they line up to different libraries in PLEX and inappropriate things could end up in the wrong library. I think this would work best as a setting to define a default root path. If it is not specified you can default to current behavior.

**Comment by kiranshila** [comment]
Default rootfolders have been added in 3.4.0
