### ISSUE TITLE
Feature - Create issues in Oversser

### ISSUE THREAD

**Issue by bakes82** [kiranshila/Doplarr#74]
**Is your feature request related to a problem? Please describe.**
Ability to make overseer media issue reports.

**Describe the solution you'd like**
Ability to make overseer media issue reports from discord just like requesting media.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by kiranshila** [comment]
I've decided that I don't think we should implement this feature. I'd prefer this app to be as lightweight and generic as possible. Bringing in functionality specific to a backend kinda breaks that model. I'd like to keep this as "general media requests" and not a frontend for Overseerr as Overseerr itself will always provide the better UX.
