### ISSUE TITLE
Root folder mapping issue

### ISSUE THREAD

**Issue by vtyr** [kiranshila/Doplarr#84]
**Describe the bug**
When running Doplarr on Windows using Java, setting the rootfolder for Radarr/Sonarr doesn't appear to work. I've tried the following:

```
 :radarr/rootfolder "H"
 :sonarr/rootfolder "G"
```

or 

```
 :radarr/rootfolder "H:"
 :sonarr/rootfolder "G:"
```

Result: User is still asked to choose the rootfolder

Also tried:

```
 :radarr/rootfolder "H:\"
 :sonarr/rootfolder "G:\"
```

Result: Application crashes, see image:
![image](https://user-images.githubusercontent.com/32479561/173166776-1f2116f1-1d20-4b50-b0d5-cb5b35a58705.png)

**Expected behavior**
The user is not met with the option to choose a folder for the requested media download, and is instead only asked to pick media and the quality profile.

**Comment by vtyr** [comment]
Escaping with double quotes as below fixes the crash, but still results in the user being asked to choose a root folder.

``
 :radarr/rootfolder "H:\\"
 :sonarr/rootfolder "G:\\"
``

**Comment by kiranshila** [comment]
Yeah these are C-style strings here, so slashes have to be escaped. I'm glad you got it working!

**Comment by vtyr** [comment]
Thanks, really well done - nice little app. Would it be possible to update the docs just to explain the above solution a tad? I don't mind doing it if I'm able to (I don't tend to clone/pull on Github, let alone if you can on github.io - I'm an Atlassian user!)

**Comment by kiranshila** [comment]
Yeah this should certainly be in the docs. They are automatically generated from markdown files in the docs directory, so if you fork and send a PR, all you need to do is add things to https://github.com/kiranshila/Doplarr/blob/main/docs/configuration.md

**Comment by notsointeresting** [comment]
hello! 

I am having a similar issue even though I am trying to implement the solution given.

When` :sonarr/rootfolder "H:\\Plex Media\\TV"` is used, it still asks users to select a root folder. 
I have also tried :sonarr/rootfolder `"H:\\Plex Media\TV"`

any help is appreciated, thanks!
