### ISSUE TITLE
Season Folders

### ISSUE THREAD

**Issue by vtyr** [kiranshila/Doplarr#87]
**Is your feature request related to a problem? Please describe.**
TV Shows added by Doplarr are not stored in season folders

**Describe the solution you'd like**
A config option to set season folders on/off

**Describe alternatives you've considered**
Alternative at the moment is requesting and then loading up Sonarr and editing the TV Show to sort into season folders

**Comment by kiranshila** [comment]
Thais was fixed in v3.6.0 with commit https://github.com/kiranshila/Doplarr/commit/f8bee903923f900da21233bb5343fe364920542d
